version: '2'
services:
  mysql:
    image: mysql:5.7
    command: mysqld --datadir=/tmpfs
    tmpfs: /tmpfs
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: kolide
      MYSQL_USER: kolide
      MYSQL_PASSWORD: kolide
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:3.2.4
    ports:
      - "6379:6379"
