---
apiVersion: k8s.kolide.com/v1alpha1
kind: OsqueryPack
metadata:
  name: osquery_monitoring
spec:
  targets:
    labels:
      - all_hosts
  queries:
    - name: osquery_version
      interval: 7200
      snapshot: true
    - name: osquery_schedule
      interval: 7200
      removed: false
    - name: osquery_events
      interval: 86400
      removed: false
    - name: oquery_info
      interval: 600
      removed: false
