---
apiVersion: v1
kind: pack
spec:
  name: osquery_monitoring
  targets:
    labels:
      - all_hosts
  queries:
    - query: osquery_version
      name: osquery_version_snapshot
      interval: 7200
      snapshot: true
    - query: osquery_version
      name: osquery_version_differential
      interval: 7200
    - query: osquery_schedule
      interval: 7200
      removed: false
    - query: osquery_events
      interval: 86400
      removed: false
    - query: oquery_info
      interval: 600
      removed: false
