version: 2
jobs:
  build:
    docker:
        - image: kolide/kolide-builder:ubuntu
          environment:
              MYSQL_TEST: true
              REDIS_TEST: true
              MYSQL_PORT_3306_TCP_ADDR: 127.0.0.1
        - image: redis
        - image: mysql:5.7
          command: mysqld --datadir=/tmpfs  --slow_query_log=1 --log_output=TABLE --log-queries-not-using-indexes
          tmpfs: /tmpfs
          environment:
              MYSQL_ROOT_PASSWORD: toor
              MYSQL_DATABASE: kolide
              MYSQL_USER: kolide
              MYSQL_PASSWORD: kolide
              MYSQL_ROOT_HOST: '%'
    working_directory: /go/src/github.com/kolide/kolide
    # ugh
    steps:
      - checkout
      - run: make deps
      - run: make generate
      - run: make test-go
      - run: make build
