version: 2
jobs:
  build-go1.9:
    docker:
        - image: kolide/fleet-builder:1.9
    working_directory: /go/src/github.com/kolide/fleet
    steps: &steps
      - checkout
      - restore_cache:
          keys:
            - vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - vendor-cache-{{ .Branch }}
            - vendor-cache

      - run: make deps
      - save_cache:
          key: vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache-{{ .Branch }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache
          paths:
            - vendor

      - run: make generate
      - run: make test
      - run: make build

workflows:
  version: 2
  build:
    jobs:
      - build-go1.9
