version: 2
jobs:
  build:
    docker:
        - image: kolide/kolide-builder:ubuntu
    working_directory: /go/src/github.com/kolide/kolide
    # ugh
    steps:
      - checkout
      - run: make deps
      - run: make generate
      - run: make build
