---
version: '2'

services:
  ubuntu14-osquery:
    image: "kolide/osquery:${KOLIDE_OSQUERY_VERSION}"
    volumes: &default-volumes
      - ./kolide.crt:/etc/osquery/kolide.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
    environment: &default-environment
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: &default-command osqueryd --flagfile=/etc/osquery/osquery.flags
    ulimits: &default-ulimits
      core:
        hard:  1000000000
        soft:  1000000000

  ubuntu16-osquery:
    image: "kolide/ubuntu16-osquery:${KOLIDE_OSQUERY_VERSION}"
    volumes: *default-volumes
    environment: *default-environment
    command: *default-command
    ulimits: *default-ulimits

  centos7-osquery:
    image: "kolide/centos7-osquery:${KOLIDE_OSQUERY_VERSION}"
    volumes: *default-volumes
    environment: *default-environment
    command: *default-command
    ulimits: *default-ulimits

  centos6-osquery:
    image: "kolide/centos6-osquery:${KOLIDE_OSQUERY_VERSION}"
    volumes: *default-volumes
    environment: *default-environment
    command: *default-command
    ulimits: *default-ulimits
