apiVersion: k8s.kolide.com/v1alpha1
kind: OsqueryQuery
metadata:
  name: docker_processes
  descriptions: The docker containers processes that are running on a system.
spec:
  query: select * from docker_container_processes;
  support:
    osquery: 2.9.0
    platforms:
      - linux
      - darwin
