---
apiVersion: k8s.kolide.com/v1alpha1
kind: OsqueryQuery
metadata:
  name: osquery_version
  description: The version of the Launcher and Osquery process
spec:
  query: select launcher.version, osquery.version from kolide_launcher_info launcher, osquery_info osquery;
  support:
    launcher: 0.3.0
    osquery: 2.9.0
---
apiVersion: k8s.kolide.com/v1alpha1
kind: OsqueryQuery
metadata:
  name: osquery_schedule
  description: Report performance stats for each file in the query schedule.
spec:
  query: select name, interval, executions, output_size, wall_time, (user_time/executions) as avg_user_time, (system_time/executions) as avg_system_time, average_memory, last_executed from osquery_schedule;
---
apiVersion: k8s.kolide.com/v1alpha1
kind: OsqueryQuery
metadata:
  name: osquery_info
  description: A heartbeat counter that reports general performance (CPU, memory) and version.
spec:
  query: select i.*, p.resident_size, p.user_time, p.system_time, time.minutes as counter from osquery_info i, processes p, time where p.pid = i.pid;
---
apiVersion: k8s.kolide.com/v1alpha1
kind: OsqueryQuery
metadata:
  name: osquery_events
  description: Report event publisher health and track event counters.
spec:
  query: select name, publisher, type, subscriptions, events, active from osquery_events;
