apiVersion: k8s.kolide.com/v1alpha1
kind: OsqueryFIM
spec:
  fim:
    interval: 500
    groups:
      - name: etc
        paths:
          - /etc/%%
      - name: users
        paths:
          - /Users/%/Library/%%
          - /Users/%/Documents/%%

